#include <stdio.h>
#include <conio.h>
void main()
{
    int num,n1,n2,n3,n4,ev,od;
    printf("enter a five digit number");
    scanf("%d",&num);
    n1=num%10;
    num=num/10;
    n2=num%10;
    num=num/10;
    n3=num%10;
    num=num/10;
    n4=num%10;
    num=num/10;
    if(n1%2==0)
    {
        ("ev=ev+n1");
    }
    else
    {
        ("od=od+n1");
    }
    if(n2%2==0)
    {
        ("ev=ev+n2");
    }
    else
    {
        ("od=od+n2");
    }
    if(n3%2==0)
    {
        ("ev=ev+n3");
    }
    else
    {
        ("od=od+n3");
    }
    if(n4%2==0)
    {
        ("ev=ev+n4");
    }
    else
    {
        ("od=od+n4");
    }
    if(num%2==0)
    {
        ("ev=ev+num");
    }
    else
    {
        ("od=od+num");
    }
    printf("%d",ev);
    printf("%d",od);
    getch();
}
